name: Build Test
on:
  pull_request:
    paths-ignore:
    - Bootloader/**
    - Copy to SD Card root directory to update/**
    - images/**
    - readme/**
    - '**/*.md'
  push:
    paths-ignore:
    - Bootloader/**
    - Copy to SD Card root directory to update/**
    - images/**
    - readme/**
    - '**/*.md'

jobs:
  main:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Build GD MKS TFT28 V4.0 
        run: platformio run --environment MKS_GD_TFT28_V4_0
